package com.project.server.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.summary
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.duration
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.image
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.level
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.charge
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String charge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.enrollment
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private Integer enrollment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sort
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.created_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.updated_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.summary
     *
     * @return the value of course.summary
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.summary
     *
     * @param summary the value for course.summary
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.duration
     *
     * @return the value of course.duration
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.duration
     *
     * @param duration the value for course.duration
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.image
     *
     * @return the value of course.image
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.image
     *
     * @param image the value for course.image
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.level
     *
     * @return the value of course.level
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.level
     *
     * @param level the value for course.level
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.charge
     *
     * @return the value of course.charge
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.charge
     *
     * @param charge the value for course.charge
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.enrollment
     *
     * @return the value of course.enrollment
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public Integer getEnrollment() {
        return enrollment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.enrollment
     *
     * @param enrollment the value for course.enrollment
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setEnrollment(Integer enrollment) {
        this.enrollment = enrollment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sort
     *
     * @return the value of course.sort
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sort
     *
     * @param sort the value for course.sort
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.created_at
     *
     * @return the value of course.created_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.created_at
     *
     * @param createdAt the value for course.created_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.updated_at
     *
     * @return the value of course.updated_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.updated_at
     *
     * @param updatedAt the value for course.updated_at
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Jul 01 12:36:31 PDT 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", summary=").append(summary);
        sb.append(", duration=").append(duration);
        sb.append(", price=").append(price);
        sb.append(", image=").append(image);
        sb.append(", level=").append(level);
        sb.append(", charge=").append(charge);
        sb.append(", status=").append(status);
        sb.append(", enrollment=").append(enrollment);
        sb.append(", sort=").append(sort);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}