package com.project.server.dto;

import java.util.Date;

public class SectionDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.title
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.course_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.chapter_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.video
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.time
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.charge
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private String charge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sort
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.created_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.updated_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.id
     *
     * @return the value of section.id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.id
     *
     * @param id the value for section.id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.title
     *
     * @return the value of section.title
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.title
     *
     * @param title the value for section.title
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.course_id
     *
     * @return the value of section.course_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.course_id
     *
     * @param courseId the value for section.course_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.chapter_id
     *
     * @return the value of section.chapter_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.chapter_id
     *
     * @param chapterId the value for section.chapter_id
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.video
     *
     * @return the value of section.video
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.video
     *
     * @param video the value for section.video
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.time
     *
     * @return the value of section.time
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.time
     *
     * @param time the value for section.time
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.charge
     *
     * @return the value of section.charge
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public String getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.charge
     *
     * @param charge the value for section.charge
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sort
     *
     * @return the value of section.sort
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sort
     *
     * @param sort the value for section.sort
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.created_at
     *
     * @return the value of section.created_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.created_at
     *
     * @param createdAt the value for section.created_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.updated_at
     *
     * @return the value of section.updated_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.updated_at
     *
     * @param updatedAt the value for section.updated_at
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated Sat Jun 27 16:43:45 PDT 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", courseId=").append(courseId);
        sb.append(", chapterId=").append(chapterId);
        sb.append(", video=").append(video);
        sb.append(", time=").append(time);
        sb.append(", charge=").append(charge);
        sb.append(", sort=").append(sort);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}